include("Gaussian.jl")
include("ColdVDF.jl")
include("separable.jl")
include("Maxwellian.jl")
include("RingBeam.jl")
include("MaxwellJuttner.jl")
include("GridVDF.jl")
include("ReducedVDF.jl")
include("relativistic.jl")
include("CoupledVDF.jl")
include("residue_cycles.jl")
include("LowRankVDF.jl")
include("Kappa.jl")
include("BiKappa.jl")


_vth(sc::Scales) = isnothing(sc.vth_para) ? throw(
    ArgumentError("No thermal speed was given: set `T`, `beta` or `vth` on the Species")
) : (sc.vth_perp, sc.vth_para)

GaussianRing(sc::Scales; kw...) = GaussianRing(; vth=_vth(sc), kw...)
ProductBiKappa(sc::Scales; kw...) = ProductBiKappa(; vth=_vth(sc), kw...)
BiKappa(sc::Scales; kw...) = BiKappa(; vth=_vth(sc), kw...)
Maxwellian(sc::Scales; kw...) = Maxwellian(; vth=_vth(sc), kw...)
MaxwellJuttner(sc::Scales) = MaxwellJuttner(2 / _vth(sc)[2]^2)