name = "VlasovMaxwellDispersion"
uuid = "cdafd680-06b3-5be4-9326-1ea31d308873"
version = "0.1.0"
authors = ["Zijin Zhang <zijin@ucla.edu>"]

[workspace]
projects = ["test", "docs", "benchmark", "lib/PlasmaBase"]

[deps]
Bumper = "8ce10254-0962-460f-a3d8-1f77fea1446e"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
HypergeometricFunctions = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NonNegLeastSquares = "b7351bd1-99d9-5c5d-8786-f205a815c4d7"
# PlasmaBase = "08180eed-d86e-466d-af9d-ca90f527ad29"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
RootsAndPoles = "a0859a10-ccb4-11e8-145d-674b3750773a"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"

# [sources]
# PlasmaBase = {path = "lib/PlasmaBase"}

[extensions]
VlasovMaxwellDispersionSciMLBaseExt = "SciMLBase"

[compat]
Bumper = "0.7"
CommonSolve = "0.2"
ForwardDiff = "1"
HypergeometricFunctions = "0.3"
LinearAlgebra = "1"
NonNegLeastSquares = "0.4"
QuadGK = "2.11"
Roots = "3.0.0"
RootsAndPoles = "2"
SciMLBase = "2, 3"
SpecialFunctions = "2"
StaticArrays = "1"
julia = "1.10"
