name: Benchmarks

on:
  pull_request_target:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'CHANGELOG.md'
      - 'test/**'
      - 'docs/**'
permissions:
  pull-requests: write    # action needs to post a comment

concurrency:
  group: benchmarks-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: MilesCranmer/AirspeedVelocity.jl@action-v1
        with:
          julia-version: '1'
          exeflags: "--threads auto,1"
        env:
          JULIA_NUM_THREADS: auto,1
