name: CI
on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - "test/**"
      - "Project.toml"
    tags: ["*"]
  pull_request:
    paths:
      - "src/**"
      - "test/**"
      - "Project.toml"
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    uses: JuliaSpacePhysics/actions/.github/workflows/julia-ci.yml@main
    with:
      env: |
        TEST_NWORKERS=2
      setup: git show-ref --verify --quiet refs/heads/main || git fetch --depth=1 origin main:main
    permissions:
      actions: write
      contents: read
    secrets: inherit
